---
# tasks file for Ambari-preparation

- name: installing NTP
  yum:
    name: ntp
    state: present
  when: inventory_hostname in groups['all']


- name: starting ntp service
  service:
    name: ntpd
    state: started
    enabled: yes
  when: inventory_hostname in groups['all']


- name: stopping firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: inventory_hostname in groups['all']