---
# tasks file for Ambari-preparation
# TODOs: the following are task to get environment prepared to install Ambari.. put them in one role "ambari-preparation"
# 1. role to collect pairs qualified domain name (FQDN) on each node (namenode, datanode) + IP address of eno1 - modify the /etc/hosts file
#    Check DNS and NSCD  https://docs.hortonworks.com/HDPDocuments/Ambari-2.6.1.0/bk_ambari-installation/content/check_dns.html
#    All hosts in your system must be configured for both forward and and reverse DNS.
#    If you are unable to configure DNS in this way, you should edit the /etc/hosts file on every host in your cluster to contain the IP address and Fully Qualified Domain Name of each of your hosts.
#    The following instructions are provided as an overview and cover a basic network setup for generic Linux hosts. Different versions and flavors of Linux might require slightly different commands and procedures.
#    Please refer to the documentation for the operating system(s) deployed in your environment.
#    Hadoop relies heavily on DNS, and as such performs many DNS lookups during normal operation. To reduce the load on your DNS infrastructure, it's highly recommended to use the Name Service Caching Daemon (NSCD)
#    on cluster nodes running Linux. This daemon will cache host, user, and group lookups and provide better resolution performance, and reduced load on DNS infrastructure.

# 2. The base directories you want to use as mount points for storing:
#    NameNode data
#    DataNodes data
#    Secondary NameNode data
#    Oozie data
#    YARN data
#    ZooKeeper data, if you install ZooKeeper
#    Various log, pid, and db files, depending on your install type

# 3. task to set passwordless ssh (run you old script for that matter)
# 4. task ​to Set Up Service User Accounts / done automatically! Use the Skip Group Modifications option to not modify the Linux groups in the cluster. Choosing this option is typically
#    required if your environment manages groups using LDAP and not on the local Linux machines.
# 5. task to install and enable NTP - DONE
#      RHEL/CentOS/Oracle 7
#      yum install -y ntp
#      systemctl enable ntpd
# 6.  task to configure iptables / stop firewalld - DONE
# 7. Disable SELinux - DONE
# 8. Disable PackageKit -- not installed on your systems... but generalize the playbook to disable it if installed
# 9. setting UMASK value - DONE
# 10. Considering setting and using local repositories? https://docs.hortonworks.com/HDPDocuments/Ambari-2.6.1.0/bk_ambari-installation/content/ch_using-local-repos.html

- name: installing NTP
  yum:
    name: ntp
    state: present
  when: inventory_hostname in groups['all']


- name: starting ntp service
  service:
    name: ntpd
    state: started
    enabled: yes
  when: inventory_hostname in groups['all']


- name: stopping firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: inventory_hostname in groups['all']


- name: Disabling SELinux
  shell: setenforce 0
  when: inventory_hostname in groups['all']
  ignore_errors: yes  # if SELinux is already disabled, the setenforce command returns rc not 0


- name: Disabling SELinux permanently... editing /etc/selinux/config to remove SELINUX=enabled
  lineinfile:
    path: /etc/selinux/config
    state: absent
    line: "SELINUX=enabled"
  when: inventory_hostname in groups['all']


- name: Disabling SELinux permanently... editing /etc/selinux/config to add SELINUX=disabled
  lineinfile:
    path: /etc/selinux/config
    state: present
    insertbefore: 'SELINUXTYPE='
    line: "SELINUX=disabled"
  when: inventory_hostname in groups['all']


- name: Setting UMASK value to 0022 for current session (read,write,exeucte permissions of 755)
  shell: umask 0022
  when: inventory_hostname in groups['all']
  ignore_errors: yes


- name: Setting UMASK value to 0022 permanently
  lineinfile:
    path: /etc/profile
    state: present
    line: "umask 0022"
  when: inventory_hostname in groups['all']