# @author: wissamabuahmad

# corner case.. first list is empty [] ??? does it treat it?

- set_fact: current_node={{ groups["data_nodes"][i|int] }}
#- name: printing mount point prefix
#  debug: var={{ hostvars['%s'|format(current_node)]["mount_point_prefix"]}}

- name: printing current node
  debug: var=current_node

- name: include.yml printing hostvars['localhost']['leftovers']
  debug: var=hostvars['localhost']['leftovers']

- name: setting batches
  set_fact: batches={{ hostvars['localhost']['leftovers'] | batch(hostvars[groups["data_nodes"][i|int]]["jbod_hdds"]) | list }}

- name: printing batches
  debug: var=batches

- name: setting scsiid_xx
  set_fact: scsiid_{{current_node}}={% if batches|length >= 1 %}{{ batches[0] }}{% else %}{{ []|list }}{% endif %}


- set_fact: x={{ 'scsiid_%s'|format(current_node) }}

- name: testing TWO-WAY DYNAMIC
  debug: var=x

- name: setting blacklist_xx
  set_fact: blacklist_{{current_node}}={{ hostvars['localhost']['scsiid2'] | difference(hostvars['localhost']['scsiid_%s'|format(current_node)]) }}


#- set_fact: mount_points_{{current_node}}={% for item in range(1, hostvars['localhost']['scsiid_%s'|format(current_node)]|length + 1) %}{{hostvars['%s'|format(current_node)]["mount_point_prefix"]}}{{item}},{% endfor %}
- set_fact: mount_points_{{current_node}}={% for item in range(0, hostvars['localhost']['scsiid_%s'|format(current_node)]|length) %}{{hostvars['%s'|format(current_node)]["mount_point_prefix"]}}{{item}},{% endfor %}
- set_fact: mount_points_{{current_node}}={{ hostvars['localhost']['mount_points_%s'|format(current_node)].split(",") }}
- set_fact: mount_points_{{current_node}}={{ hostvars['localhost']['mount_points_%s'|format(current_node)][0:-1] }}


- set_fact: scsiid_mount_points_{{current_node}}={{ hostvars['localhost']['scsiid_%s'|format(current_node)] | zip(hostvars['localhost']['mount_points_%s'|format(current_node)]) | list }}


- name: debugging scsiid_mount_points_
  debug: var="{{'scsiid_mount_points_%s'|format(current_node)}}"

- name: debugging mount_points
  debug: var="{{'mount_points_%s'|format(current_node)}}"


- name: printing scsiid_current_node...
  debug: var=scsiid_{{current_node}}

- name: printing blacklist_current_node...
  debug: var=blacklist_{{current_node}}



- name: setting leftovers
  set_fact: leftovers={% if batches|length > 1 %}{{batches[1:]}}{% else %}{{[]|list}}{%endif%}

- name: after setting leftovers...
  debug: var=hostvars['localhost']['leftovers']

- name: reassembling1...
  set_fact: leftovers={% if hostvars['localhost']['leftovers']|length != 0 %}{% for list in hostvars['localhost']['leftovers'] %}{% for x in list %}{{x}},{% endfor %}{% endfor %}{% endif %}

- name: reassembling2...
  set_fact: leftovers={{ leftovers.split(',') }}

- name: reassembling3...
  set_fact: leftovers={{ leftovers[0:-1] }}

- name: leftovers after reassembling ... printing hostvars['localhost']['leftovers']
  debug: var=hostvars['localhost']['leftovers']


- name: leftovers after reassembling ... printing leftovers
  debug: var=leftovers